### PR TITLE
wp-includes/compat.php includes _()

### LINKED ISSUE #3: Cannot redeclare _() in wordpress-stubs.php on line 94569
By just downloading the stub file and executing `php -l wordpress-stubs.php`, I got this error :

```
PHP Fatal error:  Cannot redeclare _() in wordpress-stubs.php on line 94569
```

I did not found another declaration of the `_` function, but maybe you have an idea ?

### PR DESCRIPTION
**Pull request by szepeviktor**
@GiacoCorsiglia it is a PHP built-in function: http://php.net/manual/en/function.gettext.php#example-2976

Fixes #3

### CODE REVIEW

**Comment by localheinz** [comment]
@GiacoCorsiglia 

Is there anything holding up the merge of this PR?

**Comment by localheinz** [comment]
@szepeviktor 

I have also regenerated `wordpress-stubs.php`, does this look right?

**Comment by localheinz** [comment]
@GiacoCorsiglia @szepeviktor 

I'm hesitant to merge this - as you can see from #7, which includes linting of the generated `wordpress-stubs.php`, the function `_()` is not contained (no linting errors).

What do you think?

**Comment by szepeviktor** [comment]
@localheinz In [the related issue](https://github.com/GiacoCorsiglia/wordpress-stubs/issues/3#issuecomment-457021186) I've read that @GiacoCorsiglia generated the stubs without the gettext extension.

May I suggest that the generator script should check for necessary PHP extensions?

**Comment by GiacoCorsiglia** [comment]
Hi @szepeviktor, I've run with your idea of just requiring the gettext extension for the stubs—see [this commit](https://github.com/GiacoCorsiglia/wordpress-stubs/commit/bc4fd97b0c56da6abb6ed782375fa76d7f0b0915).  Thanks for suggesting that.  I'm closing this PR for now as the original issue has been resolved.

**Comment by szepeviktor** [comment]
Okay.

**Comment by szepeviktor** [comment]
@GiacoCorsiglia Have you seen my new experiment? https://github.com/szepeviktor/wordpress-autoloaded

**Comment by GiacoCorsiglia** [comment]
Cool idea @szepeviktor.  I wonder how will stack up against [preloading](https://wiki.php.net/rfc/preload).  Maybe the two could be used together.

**Pull request closed without merging**
